"""Init pricing_db schema

Revision ID: e653fdc7d96a
Revises: 
Create Date: 2026-06-23 13:23:40.578408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e653fdc7d96a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.String(), nullable=True),
    sa.Column('feature_set', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('rate_version_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('change_detail', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('champion_assignment',
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('line')
    )
    op.create_table('model_version',
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('gini', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('deviance', sa.Float(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_desc', sa.String(), nullable=False),
    sa.Column('monotonic_applied', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('model_version_id')
    )
    op.create_table('quote',
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('pure_premium_vnd', sa.Integer(), nullable=False),
    sa.Column('final_premium_vnd', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('quote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    op.drop_table('model_version')
    op.drop_table('champion_assignment')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
