#!/usr/bin/env python3
"""Render GKE manifests for the Dynamic Pricing Platform from a single service
inventory. Deterministic + idempotent: re-running overwrites deploy/k8s/*.yaml.

Design choices baked in (match GCP_DEPLOYMENT.md §4):
  * Every app service is a private ClusterIP Deployment — only Kong is exposed.
  * Cloud SQL is reached via the **Cloud SQL Auth Proxy sidecar** on 127.0.0.1
    (no private-IP wiring needed for staging; the proxy uses Workload Identity).
  * Secrets (DB password, RabbitMQ, VNPAY) come from a k8s Secret `dpp-secrets`
    synced from Secret Manager (created by provision.sh, not committed).
  * Flyway/Alembic run as pre-deploy Jobs; serving pods set *_FLYWAY_ENABLED=false
    / RUN_MIGRATIONS=false.
  * Background workers (outbox relay + consumers) => minReplicas>=1, no
    scale-to-zero (GKE has no CPU throttling, so this "just works").

Usage: python deploy/render_k8s.py   (reads deploy/config.env)
"""
from __future__ import annotations

import pathlib
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "deploy" / "k8s"
CFG = ROOT / "deploy" / "config.env"


def _inject(text: str, marker: str, block: str) -> str:
    """Replace each line that is exactly `marker` (ignoring surrounding
    whitespace) with `block`, re-indented to that marker line's indentation.

    This runs AFTER textwrap.dedent so a multi-line block can be spliced into a
    dedented template without its own indentation corrupting the dedent's common
    -prefix calculation (the bug that flattened the Cloud SQL proxy sidecar)."""
    lines = []
    for line in text.splitlines():
        if line.strip() == marker:
            indent = line[: len(line) - len(line.lstrip())]
            lines.append(textwrap.indent(textwrap.dedent(block).rstrip("\n"), indent))
        else:
            lines.append(line)
    return "\n".join(lines) + "\n"


def load_cfg() -> dict[str, str]:
    cfg: dict[str, str] = {}
    for line in CFG.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        cfg[k.strip()] = v.strip()
    return cfg


# service -> (db env prefix or None, extra env dict, port, health path)
JAVA_SERVICES = {
    "customer-service": ("CUSTOMER", {}),
    "product-service": ("PRODUCT", {}),
    "order-service": ("ORDER", {}),
    "claims-service": ("CLAIMS", {}),
    "billing-service": ("BILLING", {
        "VNP_TMN_CODE": {"secret": "vnp-tmn-code"},
        "VNP_HASH_SECRET": {"secret": "vnp-hash-secret"},
        "VNP_PAY_URL": {"value": "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"},
        "VNP_API_URL": {"value": "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"},
    }),
    "notification-service": ("NOTIFICATION", {
        "MAIL_HOST": {"value": "mailpit.dpp.svc.cluster.local"},
        "MAIL_PORT": {"value": "1025"},
        "MAIL_FROM": {"value": "noreply@dpp-pricing.dev"},
        "NOTIFICATION_EMAIL_ENABLED": {"value": "true"},
    }),
}

DB_NAMES = {
    "CUSTOMER": "customer_db", "PRODUCT": "product_db", "ORDER": "order_db",
    "CLAIMS": "claims_db", "BILLING": "billing_db", "NOTIFICATION": "notification_db",
}


def header(cfg: str) -> str:
    return f"# GENERATED by deploy/render_k8s.py — do not edit by hand.\n# {cfg}\n"


def sqlproxy_sidecar(cfg: dict) -> str:
    inst = f"{cfg['PROJECT_ID']}:{cfg['REGION']}:{cfg['SQL_INSTANCE']}"
    return f"""\
- name: cloud-sql-proxy
  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
  args:
    - "--private-ip"
    - "--structured-logs"
    - "--port=5432"
    - "{inst}"
  securityContext:
    runAsNonRoot: true
  resources:
    requests: {{cpu: 50m, memory: 64Mi}}
"""


def java_deployment(cfg: dict, svc: str, prefix: str, extra: dict) -> str:
    img = f"{cfg['REGION']}-docker.pkg.dev/{cfg['PROJECT_ID']}/{cfg['AR_REPO']}/{svc}:{cfg['IMAGE_TAG']}"
    env_lines = [
        ("POSTGRES_USER", {"value": cfg["DB_USER"]}),
        ("POSTGRES_PASSWORD", {"secret": "db-password"}),
        ("SPRING_FLYWAY_ENABLED", {"value": "false"}),
        ("RABBITMQ_HOST", {"value": "rabbitmq.dpp.svc.cluster.local"}),
        ("RABBITMQ_PORT", {"value": "5672"}),
        ("RABBITMQ_USER", {"value": cfg["RABBITMQ_USER"]}),
        ("RABBITMQ_PASSWORD", {"secret": "rabbitmq-password"}),
        (f"{prefix}_DB_HOST", {"value": "127.0.0.1"}),
        (f"{prefix}_DB_PORT", {"value": "5432"}),
        (f"{prefix}_DB_NAME", {"value": DB_NAMES[prefix]}),
    ]
    for k, v in extra.items():
        env_lines.append((k, v))

    env_yaml = render_env(env_lines)
    body = textwrap.dedent(f"""\
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {svc}
          namespace: dpp
          labels: {{app: {svc}, tier: backend}}
        spec:
          replicas: 1
          selector: {{matchLabels: {{app: {svc}}}}}
          template:
            metadata:
              labels: {{app: {svc}, tier: backend}}
            spec:
              serviceAccountName: {svc}-sa
              containers:
              - name: {svc}
                image: {img}
                ports: [{{containerPort: 8080}}]
                env:
{textwrap.indent(env_yaml, "                ")}
                readinessProbe:
                  httpGet: {{path: /actuator/health, port: 8080}}
                  initialDelaySeconds: 30
                  periodSeconds: 10
                livenessProbe:
                  httpGet: {{path: /actuator/health, port: 8080}}
                  initialDelaySeconds: 60
                  periodSeconds: 20
                resources:
                  requests: {{cpu: 250m, memory: 512Mi}}
                  limits: {{memory: 1Gi}}
              __SQLPROXY__
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: {svc}
          namespace: dpp
        spec:
          type: ClusterIP
          selector: {{app: {svc}}}
          ports: [{{port: 8080, targetPort: 8080}}]
        ---
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: {svc}
          namespace: dpp
        spec:
          scaleTargetRef: {{apiVersion: apps/v1, kind: Deployment, name: {svc}}}
          minReplicas: 1
          maxReplicas: 4
          metrics:
          - type: Resource
            resource: {{name: cpu, target: {{type: Utilization, averageUtilization: 70}}}}
        """)
    return header(f"{svc} (Java, private ClusterIP + Cloud SQL proxy sidecar)") + _inject(body, "__SQLPROXY__", sqlproxy_sidecar(cfg))


def render_env(env_lines: list[tuple[str, dict]]) -> str:
    out = []
    for name, spec in env_lines:
        if "value" in spec:
            out.append(f"- name: {name}\n  value: \"{spec['value']}\"")
        elif "secret" in spec:
            out.append(
                f"- name: {name}\n  valueFrom:\n    secretKeyRef:\n"
                f"      name: dpp-secrets\n      key: {spec['secret']}"
            )
    return "\n".join(out)


def pricing_deployment(cfg: dict) -> str:
    img = f"{cfg['REGION']}-docker.pkg.dev/{cfg['PROJECT_ID']}/{cfg['AR_REPO']}/pricing-service:{cfg['IMAGE_TAG']}"
    db_url = f"postgresql+psycopg2://{cfg['DB_USER']}:$(POSTGRES_PASSWORD)@127.0.0.1:5432/pricing_db"
    env_lines = [
        ("POSTGRES_PASSWORD", {"secret": "db-password"}),
        ("DATABASE_URL", {"value": db_url}),
        ("PRICING_DATABASE_URL", {"value": db_url}),
        ("RUN_MIGRATIONS", {"value": "false"}),
        ("RABBITMQ_HOST", {"value": "rabbitmq.dpp.svc.cluster.local"}),
        ("RABBITMQ_PORT", {"value": "5672"}),
        ("RABBITMQ_USER", {"value": cfg["RABBITMQ_USER"]}),
        ("RABBITMQ_PASSWORD", {"secret": "rabbitmq-password"}),
        ("OBJECT_STORAGE_PROVIDER", {"value": "gcs"}),
        ("OBJECT_STORAGE_MODEL_BUCKET", {"value": cfg["BUCKET_MODELS"]}),
        ("OBJECT_STORAGE_REPORT_BUCKET", {"value": cfg["BUCKET_REPORTS"]}),
        ("OBJECT_STORAGE_DATASET_BUCKET", {"value": cfg["BUCKET_DATASETS"]}),
        ("REFERENCE_DATA_URI", {"value": f"gs://{cfg['BUCKET_REFERENCE']}"}),
        ("PRICING_REFERENCE_DIR", {"value": "/data/synthetic_real_1m_history_lift_v2"}),
        ("PRICING_MODELS_DIR", {"value": "/reports/modeling/models"}),
        ("MODEL_ARTIFACT_CACHE_DIR", {"value": "/tmp/model-cache"}),
    ]
    env_yaml = render_env(env_lines)
    body = textwrap.dedent(f"""\
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: pricing-service
          namespace: dpp
          labels: {{app: pricing-service, tier: backend}}
        spec:
          replicas: 1
          selector: {{matchLabels: {{app: pricing-service}}}}
          template:
            metadata:
              labels: {{app: pricing-service, tier: backend}}
            spec:
              serviceAccountName: pricing-runtime-sa-ksa
              containers:
              - name: pricing-service
                image: {img}
                ports: [{{containerPort: 8000}}]
                env:
{textwrap.indent(env_yaml, "                ")}
                readinessProbe:
                  httpGet: {{path: /health, port: 8000}}
                  initialDelaySeconds: 40
                  periodSeconds: 10
                livenessProbe:
                  httpGet: {{path: /health, port: 8000}}
                  initialDelaySeconds: 90
                  periodSeconds: 20
                resources:
                  requests: {{cpu: 500m, memory: 1Gi}}
                  limits: {{memory: 2Gi}}
              __SQLPROXY__
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: pricing-service
          namespace: dpp
        spec:
          type: ClusterIP
          selector: {{app: pricing-service}}
          ports: [{{port: 8000, targetPort: 8000}}]
        """)
    return header("pricing-service (FastAPI, private ClusterIP + Cloud SQL proxy + GCS reference bootstrap)") + _inject(body, "__SQLPROXY__", sqlproxy_sidecar(cfg))


def namespace_and_sa(cfg: dict) -> str:
    svcs = list(JAVA_SERVICES) + ["pricing-service"]
    sa_blocks = []
    for svc in JAVA_SERVICES:
        gsa = f"svc-{svc}@{cfg['PROJECT_ID']}.iam.gserviceaccount.com"
        sa_blocks.append(textwrap.dedent(f"""\
            ---
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: {svc}-sa
              namespace: dpp
              annotations:
                iam.gke.io/gcp-service-account: {gsa}
            """))
    # pricing uses its own runtime SA
    sa_blocks.append(textwrap.dedent(f"""\
        ---
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: pricing-runtime-sa-ksa
          namespace: dpp
          annotations:
            iam.gke.io/gcp-service-account: pricing-runtime-sa@{cfg['PROJECT_ID']}.iam.gserviceaccount.com
        """))
    return header("namespace + workload-identity service accounts") + "apiVersion: v1\nkind: Namespace\nmetadata:\n  name: dpp\n" + "".join(sa_blocks)


def rabbitmq_statefulset(cfg: dict) -> str:
    return header("RabbitMQ StatefulSet (quorum queues, definitions.json via ConfigMap)") + textwrap.dedent(f"""\
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: rabbitmq
          namespace: dpp
        spec:
          serviceName: rabbitmq
          replicas: 1
          selector: {{matchLabels: {{app: rabbitmq}}}}
          template:
            metadata:
              labels: {{app: rabbitmq}}
            spec:
              containers:
              - name: rabbitmq
                image: rabbitmq:3.13-management
                ports:
                - {{containerPort: 5672, name: amqp}}
                - {{containerPort: 15672, name: management}}
                - {{containerPort: 15692, name: prometheus}}
                env:
                - name: RABBITMQ_DEFAULT_USER
                  value: "{cfg['RABBITMQ_USER']}"
                - name: RABBITMQ_DEFAULT_PASS
                  valueFrom:
                    secretKeyRef: {{name: dpp-secrets, key: rabbitmq-password}}
                - name: RABBITMQ_ENABLED_PLUGINS_FILE
                  value: /etc/rabbitmq/enabled_plugins
                volumeMounts:
                - {{name: config, mountPath: /etc/rabbitmq/definitions.json, subPath: definitions.json}}
                - {{name: data, mountPath: /var/lib/rabbitmq}}
                readinessProbe:
                  exec: {{command: ["rabbitmq-diagnostics", "-q", "ping"]}}
                  initialDelaySeconds: 30
                  periodSeconds: 15
                resources:
                  requests: {{cpu: 250m, memory: 512Mi}}
                  limits: {{memory: 1Gi}}
              volumes:
              - name: config
                configMap: {{name: rabbitmq-definitions}}
          volumeClaimTemplates:
          - metadata: {{name: data}}
            spec:
              accessModes: ["ReadWriteOnce"]
              resources: {{requests: {{storage: 10Gi}}}}
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: rabbitmq
          namespace: dpp
        spec:
          clusterIP: None
          selector: {{app: rabbitmq}}
          ports:
          - {{port: 5672, name: amqp}}
          - {{port: 15672, name: management}}
          - {{port: 15692, name: prometheus}}
        """)


def keycloak_deployment(cfg: dict) -> str:
    db_host = "127.0.0.1"
    body = textwrap.dedent(f"""\
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: keycloak
          namespace: dpp
        spec:
          replicas: 1
          selector: {{matchLabels: {{app: keycloak}}}}
          template:
            metadata:
              labels: {{app: keycloak}}
            spec:
              serviceAccountName: keycloak-sa
              containers:
              - name: keycloak
                image: quay.io/keycloak/keycloak:26.0.7
                args: ["start", "--optimized", "--import-realm", "--hostname={cfg['AUTH_HOST']}", "--proxy-headers=xforwarded", "--http-enabled=true"]
                env:
                - name: KC_DB
                  value: postgres
                - name: KC_DB_URL
                  value: "jdbc:postgresql://{db_host}:5432/keycloak_db"
                - name: KC_DB_USERNAME
                  value: "{cfg['DB_USER']}"
                - name: KC_DB_PASSWORD
                  valueFrom:
                    secretKeyRef: {{name: dpp-secrets, key: db-password}}
                - name: KC_BOOTSTRAP_ADMIN_USERNAME
                  valueFrom:
                    secretKeyRef: {{name: dpp-secrets, key: keycloak-admin}}
                - name: KC_BOOTSTRAP_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef: {{name: dpp-secrets, key: keycloak-admin-password}}
                - name: KC_HEALTH_ENABLED
                  value: "true"
                ports:
                - {{containerPort: 8080}}
                - {{containerPort: 9000}}
                volumeMounts:
                - {{name: realm, mountPath: /opt/keycloak/data/import/realm-export.json, subPath: realm-export.json}}
                readinessProbe:
                  httpGet: {{path: /health/ready, port: 9000}}
                  initialDelaySeconds: 60
                  periodSeconds: 15
                resources:
                  requests: {{cpu: 300m, memory: 640Mi}}
                  limits: {{memory: 1280Mi}}
              volumes:
              - name: realm
                configMap: {{name: keycloak-realm}}
              __SQLPROXY__
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: keycloak
          namespace: dpp
        spec:
          type: ClusterIP
          selector: {{app: keycloak}}
          ports: [{{port: 8080, targetPort: 8080}}]
        """)
    return header("Keycloak (prod mode, Cloud SQL keycloak_db via proxy sidecar, realm imported once)") + _inject(body, "__SQLPROXY__", sqlproxy_sidecar(cfg))


def migration_jobs(cfg: dict) -> str:
    """One Job per Java service (Flyway) + one for pricing (Alembic). Run as a
    pre-deploy gate; each connects through its own Cloud SQL proxy sidecar."""
    blocks = []
    for svc, (prefix, _extra) in JAVA_SERVICES.items():
        img = f"{cfg['REGION']}-docker.pkg.dev/{cfg['PROJECT_ID']}/{cfg['AR_REPO']}/{svc}:{cfg['IMAGE_TAG']}"
        blocks.append(_inject(textwrap.dedent(f"""\
            ---
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: migrate-{svc}
              namespace: dpp
            spec:
              backoffLimit: 2
              template:
                spec:
                  restartPolicy: Never
                  serviceAccountName: {svc}-sa
                  containers:
                  - name: migrate
                    image: {img}
                    env:
                    - {{name: POSTGRES_USER, value: "{cfg['DB_USER']}"}}
                    - name: POSTGRES_PASSWORD
                      valueFrom: {{secretKeyRef: {{name: dpp-secrets, key: db-password}}}}
                    - {{name: {prefix}_DB_HOST, value: "127.0.0.1"}}
                    - {{name: {prefix}_DB_PORT, value: "5432"}}
                    - {{name: {prefix}_DB_NAME, value: "{DB_NAMES[prefix]}"}}
                    - {{name: SPRING_FLYWAY_ENABLED, value: "true"}}
                    - {{name: SPRING_MAIN_WEB_APPLICATION_TYPE, value: "none"}}
                  __SQLPROXY__
            """), "__SQLPROXY__", sqlproxy_job_sidecar(cfg)))
    # pricing alembic
    pimg = f"{cfg['REGION']}-docker.pkg.dev/{cfg['PROJECT_ID']}/{cfg['AR_REPO']}/pricing-service:{cfg['IMAGE_TAG']}"
    blocks.append(_inject(textwrap.dedent(f"""\
        ---
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: migrate-pricing
          namespace: dpp
        spec:
          backoffLimit: 2
          template:
            spec:
              restartPolicy: Never
              serviceAccountName: pricing-runtime-sa-ksa
              containers:
              - name: migrate
                image: {pimg}
                command: ["alembic", "upgrade", "head"]
                env:
                - name: DATABASE_URL
                  value: "postgresql+psycopg2://{cfg['DB_USER']}:$(POSTGRES_PASSWORD)@127.0.0.1:5432/pricing_db"
                - name: POSTGRES_PASSWORD
                  valueFrom: {{secretKeyRef: {{name: dpp-secrets, key: db-password}}}}
              __SQLPROXY__
        """), "__SQLPROXY__", sqlproxy_job_sidecar(cfg)))
    return header("DB migration Jobs (Flyway x6 + Alembic) — pre-deploy gate") + "".join(blocks)


def sqlproxy_job_sidecar(cfg: dict) -> str:
    """Proxy sidecar for Jobs — Job pods have no native sidecar lifecycle, so the
    proxy is a normal container and the migrate container exits, ending the pod.
    We use the 'quitquitquit' pattern via a shared process namespace is overkill;
    instead the migrate container's completion + restartPolicy Never bounds it."""
    inst = f"{cfg['PROJECT_ID']}:{cfg['REGION']}:{cfg['SQL_INSTANCE']}"
    return f"""\
- name: cloud-sql-proxy
  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
  args: ["--private-ip", "--port=5432", "--quitquitquit-timeout=5s", "{inst}"]
  resources:
    requests: {{cpu: 50m, memory: 64Mi}}
"""


def edge_tier(cfg: dict) -> str:
    """Kong (only public workload) + frontend SPA + GKE Ingress with a
    Google-managed cert for api./app.dpp-pricing.dev, and a default-deny
    NetworkPolicy so /internal/** is unreachable from outside the namespace."""
    api, app, auth = cfg["API_HOST"], cfg["APP_HOST"], cfg["AUTH_HOST"]
    fe_img = f"{cfg['REGION']}-docker.pkg.dev/{cfg['PROJECT_ID']}/{cfg['AR_REPO']}/frontend:{cfg['IMAGE_TAG']}"
    body = textwrap.dedent(f"""\
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: kong
          namespace: dpp
        spec:
          replicas: 1
          selector: {{matchLabels: {{app: kong}}}}
          template:
            metadata:
              labels: {{app: kong}}
            spec:
              containers:
              - name: kong
                image: kong:3.8.0
                env:
                - {{name: KONG_DATABASE, value: "off"}}
                - {{name: KONG_DECLARATIVE_CONFIG, value: /etc/kong/kong.yml}}
                - {{name: KONG_PROXY_LISTEN, value: "0.0.0.0:8000"}}
                - {{name: KONG_STATUS_LISTEN, value: "0.0.0.0:8100"}}
                - {{name: KONG_PLUGINS, value: bundled}}
                ports:
                - {{containerPort: 8000, name: proxy}}
                - {{containerPort: 8100, name: status}}
                volumeMounts:
                - {{name: kong-config, mountPath: /etc/kong/kong.yml, subPath: kong.yml}}
                readinessProbe:
                  httpGet: {{path: /status, port: 8100}}
                  initialDelaySeconds: 15
                  periodSeconds: 10
                resources:
                  requests: {{cpu: 250m, memory: 512Mi}}
                  limits: {{memory: 1Gi}}
              volumes:
              - name: kong-config
                configMap: {{name: kong-prod-config}}
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: kong
          namespace: dpp
          annotations:
            cloud.google.com/backend-config: '{{"default": "kong-backendconfig"}}'
        spec:
          type: NodePort
          selector: {{app: kong}}
          ports: [{{port: 8000, targetPort: 8000}}]
        ---
        apiVersion: cloud.google.com/v1
        kind: BackendConfig
        metadata:
          name: kong-backendconfig
          namespace: dpp
        spec:
          healthCheck:
            requestPath: /status
            port: 8100
            type: HTTP
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: frontend
          namespace: dpp
        spec:
          replicas: 1
          selector: {{matchLabels: {{app: frontend}}}}
          template:
            metadata:
              labels: {{app: frontend}}
            spec:
              containers:
              - name: frontend
                image: {fe_img}
                ports: [{{containerPort: 80}}]
                readinessProbe:
                  httpGet: {{path: /index.html, port: 80}}
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  requests: {{cpu: 50m, memory: 64Mi}}
                  limits: {{memory: 128Mi}}
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: frontend
          namespace: dpp
        spec:
          type: NodePort
          selector: {{app: frontend}}
          ports: [{{port: 80, targetPort: 80}}]
        ---
        apiVersion: networking.gke.io/v1
        kind: ManagedCertificate
        metadata:
          name: dpp-cert
          namespace: dpp
        spec:
          domains:
          - {api}
          - {app}
        ---
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: dpp-ingress
          namespace: dpp
          annotations:
            kubernetes.io/ingress.class: "gce"
            kubernetes.io/ingress.global-static-ip-name: "dpp-ingress-ip"
            networking.gke.io/managed-certificates: "dpp-cert"
        spec:
          rules:
          - host: {api}
            http:
              paths:
              - path: /
                pathType: Prefix
                backend: {{service: {{name: kong, port: {{number: 8000}}}}}}
          - host: {app}
            http:
              paths:
              - path: /
                pathType: Prefix
                backend: {{service: {{name: frontend, port: {{number: 80}}}}}}
        ---
        # Default-deny ingress into the namespace, then allow only Kong->services
        # and in-namespace traffic. Keeps /internal/** unreachable from outside dpp.
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-in-namespace
          namespace: dpp
        spec:
          podSelector: {{}}
          policyTypes: [Ingress]
          ingress:
          - from:
            - podSelector: {{}}
          - from:
            - namespaceSelector:
                matchLabels: {{kubernetes.io/metadata.name: dpp}}
        ---
        # Allow GKE LB health checks + Ingress traffic to reach Kong and frontend.
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-lb-to-edge
          namespace: dpp
        spec:
          podSelector:
            matchExpressions:
            - {{key: app, operator: In, values: [kong, frontend]}}
          policyTypes: [Ingress]
          ingress:
          - from:
            - ipBlock: {{cidr: 130.211.0.0/22}}
            - ipBlock: {{cidr: 35.191.0.0/16}}
        """)
    # Keycloak is also public (SPA logs in directly at auth.dpp-pricing.dev). It
    # gets its own cert + ingress so the OIDC issuer URL resolves over HTTPS.
    body += textwrap.dedent(f"""\
        ---
        apiVersion: networking.gke.io/v1
        kind: ManagedCertificate
        metadata:
          name: dpp-auth-cert
          namespace: dpp
        spec:
          domains: [{auth}]
        ---
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: dpp-auth-ingress
          namespace: dpp
          annotations:
            kubernetes.io/ingress.class: "gce"
            networking.gke.io/managed-certificates: "dpp-auth-cert"
        spec:
          rules:
          - host: {auth}
            http:
              paths:
              - path: /
                pathType: Prefix
                backend: {{service: {{name: keycloak, port: {{number: 8080}}}}}}
        """)
    return header("edge: Kong (public) + frontend SPA + Ingress + ManagedCertificate + NetworkPolicy") + body


def main() -> None:
    cfg = load_cfg()
    OUT.mkdir(parents=True, exist_ok=True)
    written = []

    (OUT / "00-namespace.yaml").write_text(namespace_and_sa(cfg), encoding="utf-8")
    written.append("00-namespace.yaml")

    for svc, (prefix, extra) in JAVA_SERVICES.items():
        (OUT / f"10-{svc}.yaml").write_text(java_deployment(cfg, svc, prefix, extra), encoding="utf-8")
        written.append(f"10-{svc}.yaml")

    (OUT / "11-pricing-service.yaml").write_text(pricing_deployment(cfg), encoding="utf-8")
    written.append("11-pricing-service.yaml")

    (OUT / "20-rabbitmq.yaml").write_text(rabbitmq_statefulset(cfg), encoding="utf-8")
    written.append("20-rabbitmq.yaml")

    (OUT / "21-keycloak.yaml").write_text(keycloak_deployment(cfg), encoding="utf-8")
    written.append("21-keycloak.yaml")

    (OUT / "90-migrations.yaml").write_text(migration_jobs(cfg), encoding="utf-8")
    written.append("90-migrations.yaml")

    (OUT / "30-edge.yaml").write_text(edge_tier(cfg), encoding="utf-8")
    written.append("30-edge.yaml")

    print(f"Wrote {len(written)} manifest(s) to {OUT}:")
    for w in written:
        print(f"  {w}")


if __name__ == "__main__":
    main()
