server:
  port: 8080

spring:
  application:
    name: claims-service
  datasource:
    url: jdbc:postgresql://${CLAIMS_DB_HOST:localhost}:${CLAIMS_DB_PORT:5437}/${CLAIMS_DB_NAME:claims_db}
    username: ${POSTGRES_USER:platform_user}
    password: ${POSTGRES_PASSWORD:platform_password_dev_only}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:platform_user}
    password: ${RABBITMQ_PASSWORD:platform_password_dev_only}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/claims

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs